### ISSUE TITLE
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

### ISSUE THREAD

**Issue by muhazmi** [mjumain/RBAC-LARAVEL-9#1]
Muncul error tersebut di laravel 10. Error tetap muncul meskipun sudah menjalankan composer install dan composer update.

**Comment by muhazmi** [comment]
![Screenshot 2024-02-06 134503](https://github.com/mjumain/RBAC-LARAVEL-9/assets/22718017/69d5c7cf-3803-4a89-92ee-e8e99e2f970b)

**Comment by mjumain** [comment]
coba di git pull lagi mas, disaya aman ini mas

**Comment by muhazmi** [comment]
ok udah bisa mas
